# Generated by Django 3.0.5 on 2020-04-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User_id',
            new_name='email',
        ),
    ]
